#ifndef MIC_ARRAY_CONF_H_
#define MIC_ARRAY_CONF_H_

#define MIC_ARRAY_MAX_FRAME_SIZE_LOG2 0
#define MIC_ARRAY_NUM_MICS (8)
#define MIC_ARRAY_CHANS_PER_DECIMATOR (2)
#define MIC_ARRAY_DECIMATORS (MIC_ARRAY_NUM_MICS / MIC_ARRAY_CHANS_PER_DECIMATOR)

#endif /* MIC_ARRAY_CONF_H_ */
